FROM public.ecr.aws/lambda/python:3.9

RUN pip install --upgrade pip

COPY ./env/requirements.txt .
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./src ${LAMBDA_TASK_ROOT}/src/

RUN python ${LAMBDA_TASK_ROOT}/src/pred/models/torch_pred.py
CMD ["src.app.app.handler"]
